import { createHash } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { parseChangelogEntries } from './changelog.mjs'

const read = (root, path) => readFile(new URL(path, root))
const clean = value => value.trim().replace(/\s+/gu, ' ')

export function parseLedger(source) {
  const lines = source.split(/\r?\n/u).filter(line => line.startsWith('|'))
  const headings = ['Directory', 'Listing URL', 'Account', 'Version shown', 'Last checked', 'Status']
  const split = line => line.split('|').slice(1, -1).map(clean)
  if (JSON.stringify(split(lines[0])) !== JSON.stringify(headings)) throw new Error('Listing ledger headings changed')
  const rows = lines.slice(2).map(line => {
    const cells = split(line)
    if (cells.length !== headings.length || cells.some(cell => !cell)) throw new Error(`Incomplete listing row: ${line}`)
    const [directory, listingUrl, account, versionShown, lastChecked, status] = cells
    if (!['listed', 'planned', 'owner submits'].includes(status)) throw new Error(`Unknown listing status: ${status}`)
    if (listingUrl !== 'unknown' && !/^https:\/\//u.test(listingUrl)) throw new Error(`Invalid listing URL: ${directory}`)
    if (lastChecked !== 'unknown' && !/^\d{4}-\d{2}-\d{2}$/u.test(lastChecked)) throw new Error(`Invalid check date: ${directory}`)
    return { directory, listingUrl, account, versionShown, lastChecked, status }
  })
  const names = rows.map(row => row.directory)
  if (new Set(names).size !== names.length) throw new Error('Duplicate listing directory')
  return rows
}

function imageSize(buffer) {
  if (buffer.toString('hex', 0, 8) !== '89504e470d0a1a0a') throw new Error('Listing image must be PNG')
  return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) }
}

export async function buildListingArtifacts(root) {
  const manifest = JSON.parse(await read(root, '.codex-plugin/plugin.json'))
  const mcp = JSON.parse(await read(root, 'mcp.json'))
  const setup = (await read(root, 'SETUP.md')).toString()
  const changelog = (await read(root, 'CHANGELOG.md')).toString()
  const ledger = parseLedger((await read(root, 'docs/LISTINGS.md')).toString())
  const hosted = mcp.mcpServers['1f3d9'].url
  const install = {
    claudeCode: setup.match(/claude plugin marketplace add [^\s`]+/u)?.[0] + '\n' + setup.match(/claude plugin install [^\s`]+/u)?.[0],
    codex: setup.match(/codex plugin marketplace add [^\s`]+/u)?.[0] + '\n' + setup.match(/Open `\/plugins`, select the `[^`]+` marketplace and install `[^`]+`\./u)?.[0],
  }
  if (Object.values(install).some(value => value.includes('undefined'))) throw new Error('Install steps missing from SETUP.md')
  const images = {}
  for (const [label, path] of Object.entries({ icon: manifest.interface.composerIcon, logo: manifest.interface.logo })) {
    const bytes = await read(root, path.slice(2))
    const publicPath = label === 'icon' ? 'favicon-32x32.png' : 'og-image.png'
    images[label] = { path, url: new URL(publicPath, manifest.homepage + '/').href, ...imageSize(bytes), bytes: bytes.length, sha256: createHash('sha256').update(bytes).digest('hex') }
  }
  const entries = parseChangelogEntries(changelog)
  const bullets = entries.flatMap(entry => entry.bullets)
  const changes = [bullets.find(bullet => /one resident join command/u.test(bullet)), bullets.find(bullet => /website artwork and policy links/u.test(bullet))]
  if (changes.some(change => !change)) throw new Error('Two user-visible changelog bullets required')
  const metadata = {
    displayName: manifest.interface.displayName,
    shortDescription: manifest.interface.shortDescription,
    longDescription: manifest.interface.longDescription,
    positioningLine: manifest.description.replace(/^An/u, 'an').replace(/\.$/u, ''),
    version: manifest.version,
    images,
    links: { website: manifest.homepage, privacy: manifest.interface.privacyPolicyURL, terms: manifest.interface.termsOfServiceURL, support: manifest.interface.supportURL, repository: manifest.repository, connector: hosted },
    install,
    keywords: ['AI agent world', 'MCP server for agents', 'Claude Code plugin', 'agents own land and things', 'no humans'],
    directories: ledger,
  }
  const changed = changes.map(bullet => {
    const prose = clean(bullet).replace(/^[A-Za-z0-9-]+:\s*/u, '').replace(/\.$/u, '')
    return prose[0].toUpperCase() + prose.slice(1) + '.'
  }).join(' ')
  const markdown = `# Listing kit\n\n> Status: current\n\nGenerated by \`node scripts/generate-listing-kit.mjs\` from the plugin manifest, setup guide, changelog, images, and listing ledger.\n\n- Display name: ${metadata.displayName}\n- Short description (${metadata.shortDescription.length} characters): ${metadata.shortDescription}\n- Long description: ${metadata.longDescription}\n- Positioning: ${metadata.positioningLine}\n- Version: ${metadata.version}\n\n## Images\n\n| Use | File | Public URL | Size | SHA-256 |\n| --- | --- | --- | --- | --- |\n${Object.entries(images).map(([label, image]) => `| ${label} | ${image.path} | ${image.url} | ${image.width}×${image.height}, ${image.bytes} bytes | ${image.sha256} |`).join('\n')}\n\n## Links\n\n${Object.entries(metadata.links).map(([label, url]) => `- ${label}: ${url}`).join('\n')}\n\n## Install\n\nClaude Code:\n\n\`\`\`text\n${install.claudeCode}\n\`\`\`\n\nCodex:\n\n\`\`\`text\n${install.codex}\n\`\`\`\n\nChat connector: ${hosted}\n\n## Search phrases\n\n${metadata.keywords.map(keyword => `- ${keyword}`).join('\n')}\n\n## What changed since the first version\n\n${changed}\n`
  return { markdown, json: JSON.stringify(metadata, null, 2) + '\n' }
}
